MACRO(START message)
    message(\n========================= " " ${message} " " =========================)
ENDMACRO()

MACRO(END message)
    message(========================= " " ${message} " " =========================\n)
ENDMACRO()

MACRO(SUBDIR_LIST result current_dir)
    FILE(GLOB children RELATIVE ${current_dir} ${current_dir}/*)
    SET(dirlist "")
    FOREACH(child ${children})
        IF(IS_DIRECTORY ${current_dir}/${child})
            LIST(APPEND dirlist ${child})
        ENDIF()
    ENDFOREACH()
    SET(${result} ${dirlist})
ENDMACRO()

MACRO(LOG_LIST vars title)
    message("[" ${title} "]: ")
    foreach (var ${${vars}})
        message("     " ${var})
    endforeach ()
ENDMACRO()
